# See https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
_extends: .github
tag-template: filesystem_scm-$NEXT_MINOR_VERSION

categories:
  - title: 💥 Breaking Changes
    label: breaking
  - title: 🚀 New Features
    label: feature
  - title: ✨ Improvements
    label: enhancement
  - title: 🐛 Bug Fixes
    label: bug
  - title: 📝 Documentation
    label: documentation
  - title: 📦 Dependency Updates
    label: dependencies
  - title: 🔧 Internal Changes
    label: internal
  - title: 🚦 Tests
    label: tests

exclude-labels:
  - 'skip-changelog'
